[build]
  publish = "public"
  functions = "netlify/functions"
  command = "bash ./build.sh"

[dev]
  publish = "public"
  functions = "netlify/functions"
  port = 8888
  
[build.environment]
  NODE_ENV = "production"
  NETLIFY = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"