[build]
  publish = "public"
  functions = "netlify/functions"
  command = "chmod +x ./build.sh && ./build.sh"

[dev]
  publish = "public"
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200